name: lingkung_partner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_storage:
  firebase_core:
  cloud_firestore:
  provider:
  uuid:
  intl:
  image_picker:
  image_picker_gallery_camera: ^0.1.6
  image_cropper: ^1.2.3
  carousel_pro:
  flutter_typeahead:
  flutter_spinkit:
  # curved_navigation_bar:
  bottom_navy_bar: ^5.4.0
  introduction_screen:
  shared_preferences:
  stripe_payment:
  cached_network_image: ^2.0.0-rc
  flutter_inappwebview: ^4.0.0+4
  circular_check_box: ^1.0.3
  google_maps_flutter: 
  location: ^3.0.0
  geolocator: ^5.3.2+2
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.18
  http: ^0.12.2
  geocoder: ^0.1.2
  # permission_handler: ^5.0.1+1
  # google_maps_place_picker: ^0.10.0
  # tuple: ^1.0.3
  # google_map_location_picker: ^3.3.5
  country_code_picker: ^1.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/images/iconlogos.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/trashBank/
    # - assets/images/trash/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto-Medium.ttf
         - asset: assets/fonts/Roboto-Bold.ttf
  #         style: italic
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
